//! Observational equivalence generated by finite operation tests (Section 3.3).
//! Labels may denote forwards or already yielded inverses. Definedness is part
//! of the observation, and inverse labels carry no outcome (`None`).
use vstd::prelude::*;

verus! {
pub type Operation<S,L,O> = spec_fn(L,S)->Option<(S,Option<O>)>;

pub open spec fn test<S,L,O>(op:Operation<S,L,O>,word:Seq<L>,s:S) -> Option<Seq<Option<O>>>
    decreases word.len(),
{
    if word.len()==0 {Some(Seq::empty())}
    else {match op(word.first(),s) {
        None=>None,
        Some((next,outcome))=>match test(op,word.drop_first(),next) {
            None=>None, Some(rest)=>Some(seq![outcome]+rest),
        },
    }}
}
pub open spec fn indistinguishable<S,L,O>(op:Operation<S,L,O>,a:S,b:S) -> bool {
    forall|word:Seq<L>| #[trigger] test(op,word,a)==test(op,word,b)
}
pub open spec fn respects<S,L,O>(op:Operation<S,L,O>,eq:spec_fn(S,S)->bool) -> bool {
    forall|label:L,a:S,b:S| #![trigger op(label,a),op(label,b)] eq(a,b) ==> {
        &&& op(label,a).is_some()==op(label,b).is_some()
        &&& (op(label,a).is_some() ==> op(label,a).unwrap().1==op(label,b).unwrap().1
            && eq(op(label,a).unwrap().0,op(label,b).unwrap().0))
    }
}
pub proof fn test_prefix<S,L,O>(op:Operation<S,L,O>,label:L,word:Seq<L>,s:S)
    ensures test(op,seq![label]+word,s) == match op(label,s) {
        None=>None,Some((next,outcome))=>match test(op,word,next) {
            None=>None,Some(rest)=>Some(seq![outcome]+rest),
        }
    },
{
    assert((seq![label]+word).first()==label);
    assert((seq![label]+word).drop_first() =~= word);
}

/// Lemma 32(1): equivalence follows from equality of all finite observations.
pub proof fn observational_equivalence<S,L,O>(op:Operation<S,L,O>)
    ensures crate::calculus::equivalence(|a:S,b:S|indistinguishable(op,a,b)),
{ }

/// Prefixing arbitrary tests derives successor respect, rather than postulating
/// it as an additional axiom of the observational relation.
pub proof fn operations_respect_observations<S,L,O>(op:Operation<S,L,O>)
    ensures respects(op,|a:S,b:S|indistinguishable(op,a,b)),
{
    assert forall|label:L,a:S,b:S| #![trigger op(label,a),op(label,b)] indistinguishable(op,a,b) implies {
        &&& op(label,a).is_some()==op(label,b).is_some()
        &&& (op(label,a).is_some() ==> op(label,a).unwrap().1==op(label,b).unwrap().1
            && indistinguishable(op,op(label,a).unwrap().0,op(label,b).unwrap().0))
    } by {
        test_prefix(op,label,Seq::empty(),a);test_prefix(op,label,Seq::empty(),b);
        assert(seq![label]+Seq::empty() =~= seq![label]);
        assert(test(op,seq![label],a)==test(op,seq![label],b));
        if op(label,a).is_some() {
            assert(op(label,b).is_some());
            let left=op(label,a).unwrap();let right=op(label,b).unwrap();
            assert(test(op,seq![label],a)==Some(seq![left.1]));
            assert(test(op,seq![label],b)==Some(seq![right.1]));
            assert(seq![left.1][0]==seq![right.1][0]);
            assert(left.1==right.1);
            assert forall|word:Seq<L>| #[trigger] test(op,word,left.0)==test(op,word,right.0) by {
                test_prefix(op,label,word,a);test_prefix(op,label,word,b);
                assert(test(op,seq![label]+word,a)==test(op,seq![label]+word,b));
                if test(op,word,left.0).is_some() && test(op,word,right.0).is_some() {
                    let xs=test(op,word,left.0).unwrap();let ys=test(op,word,right.0).unwrap();
                    assert(seq![left.1]+xs==seq![right.1]+ys);
                    assert(xs.len()==ys.len());
                    assert(xs =~= ys) by {
                        assert forall|i:int| 0<=i<xs.len() implies xs[i]==ys[i] by {
                            assert((seq![left.1]+xs)[i+1]==(seq![right.1]+ys)[i+1]);
                        }
                    }
                }
            }
        }
    }
}

pub proof fn respecting_test<S,L,O>(op:Operation<S,L,O>,eq:spec_fn(S,S)->bool,word:Seq<L>,a:S,b:S)
    requires respects(op,eq),eq(a,b),
    ensures test(op,word,a)==test(op,word,b),
    decreases word.len(),
{
    if word.len()>0 {
        assert(op(word.first(),a).is_some()==op(word.first(),b).is_some());
        if op(word.first(),a).is_some() {
            let left=op(word.first(),a).unwrap();let right=op(word.first(),b).unwrap();
            assert(eq(left.0,right.0));assert(left.1==right.1);
            respecting_test(op,eq,word.drop_first(),left.0,right.0);
        }
    }
}
/// Lemma 32(2): any operation-respecting relation is contained in test equality.
pub proof fn coarsest_observational_relation<S,L,O>(op:Operation<S,L,O>,eq:spec_fn(S,S)->bool,a:S,b:S)
    requires respects(op,eq),eq(a,b),
    ensures indistinguishable(op,a,b),
{
    assert forall|word:Seq<L>| #[trigger] test(op,word,a)==test(op,word,b) by {
        respecting_test(op,eq,word,a,b);
    }
}

pub open spec fn related_maps<S>(eq:spec_fn(S,S)->bool,f:spec_fn(S)->S,g:spec_fn(S)->S) -> bool {
    forall|a:S,b:S| eq(a,b) ==> #[trigger] eq(f(a),g(b))
}
/// Lemma 35 on maps: a partial equivalence, not unconditional reflexivity.
pub proof fn map_partial_equivalence<S>(eq:spec_fn(S,S)->bool,f:spec_fn(S)->S,
    g:spec_fn(S)->S,h:spec_fn(S)->S)
    requires crate::calculus::equivalence(eq),
    ensures related_maps(eq,f,g) ==> related_maps(eq,g,f),
        related_maps(eq,f,g) && related_maps(eq,g,h) ==> related_maps(eq,f,h),
        related_maps(eq,f,g) ==> related_maps(eq,f,f) && related_maps(eq,g,g),
{
    if related_maps(eq,f,g) {
        assert forall|a:S,b:S| eq(a,b) implies #[trigger] eq(g(a),f(b)) by {
            assert(eq(b,a));assert(eq(f(b),g(a)));
        }
        assert forall|a:S,b:S| eq(a,b) implies #[trigger] eq(f(a),f(b)) by {
            assert(eq(f(a),g(b)));assert(eq(b,b));assert(eq(g(b),f(b)));
        }
        assert forall|a:S,b:S| eq(a,b) implies #[trigger] eq(g(a),g(b)) by {
            assert(eq(g(a),f(b)));assert(eq(b,b));assert(eq(f(b),g(b)));
        }
        if related_maps(eq,g,h) {
            assert forall|a:S,b:S| eq(a,b) implies #[trigger] eq(f(a),h(b)) by {
                assert(eq(f(a),g(b)));assert(eq(b,b));assert(eq(g(b),h(b)));
            }
        }
    }
}

pub open spec fn context_equal<K,V>(eq:spec_fn(K,V,V)->bool,keys:ISet<K>,a:IMap<K,V>,b:IMap<K,V>) -> bool {
    &&& forall|k:K| keys.contains(k) ==> a.dom().contains(k)==b.dom().contains(k)
    &&& forall|k:K| keys.contains(k) && a.dom().contains(k) ==> eq(k,a[k],b[k])
}
proof fn equivalence_at<V>(eq:spec_fn(V,V)->bool,a:V,b:V,c:V)
    requires crate::calculus::equivalence(eq),
    ensures eq(a,a),eq(a,b) ==> eq(b,a),eq(a,b) && eq(b,c) ==> eq(a,c),
{ }
/// Definition 33: related domains imply identical dependency satisfaction.
pub proof fn context_equivalence<K,V>(eq:spec_fn(K,V,V)->bool,keys:ISet<K>)
    requires forall|k:K| keys.contains(k) ==> crate::calculus::equivalence(|a:V,b:V|eq(k,a,b)),
    ensures crate::calculus::equivalence(|a:IMap<K,V>,b:IMap<K,V>|context_equal(eq,keys,a,b)),
{
    assert forall|a:IMap<K,V>| #[trigger] context_equal(eq,keys,a,a) by {
        assert forall|k:K| keys.contains(k) && a.dom().contains(k) implies eq(k,a[k],a[k]) by {
            assert(crate::calculus::equivalence(|x:V,y:V|eq(k,x,y)));
            equivalence_at(|x:V,y:V|eq(k,x,y),a[k],a[k],a[k]);
        }
    }
    assert forall|a:IMap<K,V>,b:IMap<K,V>| context_equal(eq,keys,a,b) implies #[trigger] context_equal(eq,keys,b,a) by {
        assert forall|k:K| keys.contains(k) && b.dom().contains(k) implies eq(k,b[k],a[k]) by {
            assert(a.dom().contains(k));assert(eq(k,a[k],b[k]));
            assert(crate::calculus::equivalence(|x:V,y:V|eq(k,x,y)));
            equivalence_at(|x:V,y:V|eq(k,x,y),a[k],b[k],a[k]);
        }
    }
    assert forall|a:IMap<K,V>,b:IMap<K,V>,c:IMap<K,V>| #[trigger] context_equal(eq,keys,a,b) && #[trigger] context_equal(eq,keys,b,c)
        implies context_equal(eq,keys,a,c) by {
        assert forall|k:K| keys.contains(k) && a.dom().contains(k) implies eq(k,a[k],c[k]) by {
            assert(b.dom().contains(k));assert(eq(k,a[k],b[k]));assert(eq(k,b[k],c[k]));
            assert(crate::calculus::equivalence(|x:V,y:V|eq(k,x,y)));
            equivalence_at(|x:V,y:V|eq(k,x,y),a[k],b[k],c[k]);
        }
    }
}
pub proof fn related_satisfaction<K,V>(eq:spec_fn(K,V,V)->bool,keys:ISet<K>,deps:ISet<K>,a:IMap<K,V>,b:IMap<K,V>)
    requires context_equal(eq,keys,a,b),deps.subset_of(keys),
    ensures deps.subset_of(a.dom())==deps.subset_of(b.dom()),
{
    assert forall|k:K| deps.contains(k) implies a.dom().contains(k)==b.dom().contains(k) by { }
}

pub open spec fn related_effects<S>(eq:spec_fn(S,S)->bool,
    f:spec_fn(S)->crate::foundations::Tracked<S>,g:spec_fn(S)->crate::foundations::Tracked<S>) -> bool
{
    forall|a:S,b:S| #![trigger f(a),g(b)] eq(a,b) ==> {
        &&& eq(f(a).value,g(b).value)
        &&& related_maps(eq,f(a).undo,g(b).undo)
    }
}
/// Definition 36 includes inverse respect, not merely a recovery equation.
pub open spec fn witnessed_effect<S>(eq:spec_fn(S,S)->bool,e:spec_fn(S)->crate::foundations::Tracked<S>) -> bool {
    related_effects(eq,e,e) && forall|x:S| #[trigger] eq((e(x).undo)(e(x).value),x)
}

pub proof fn compose_related<S>(eq:spec_fn(S,S)->bool,f:spec_fn(S)->S,g:spec_fn(S)->S,
    h:spec_fn(S)->S,j:spec_fn(S)->S)
    requires related_maps(eq,f,g),related_maps(eq,h,j),
    ensures related_maps(eq,crate::foundations::compose(f,h),crate::foundations::compose(g,j)),
{ }

/// Lemma 38 / Theorem 11 in the observational quotient. The two actual yields
/// may contain different inverses, provided those inverses are related maps.
pub proof fn witnessed_effect_composition<S>(eq:spec_fn(S,S)->bool,
    f:spec_fn(S)->crate::foundations::Tracked<S>,g:spec_fn(S)->crate::foundations::Tracked<S>)
    requires crate::calculus::equivalence(eq),witnessed_effect(eq,f),witnessed_effect(eq,g),
    ensures witnessed_effect(eq,|x:S|crate::foundations::diamond(f,g,x)),
{
    let composed=|x:S|crate::foundations::diamond(f,g,x);
    assert forall|a:S,b:S| #![trigger composed(a),composed(b)] eq(a,b) implies {
        &&& eq(composed(a).value,composed(b).value)
        &&& related_maps(eq,composed(a).undo,composed(b).undo)
    } by {
        assert(eq(g(a).value,g(b).value));
        assert(related_maps(eq,g(a).undo,g(b).undo));
        assert(related_maps(eq,f(g(a).value).undo,f(g(b).value).undo));
        compose_related(eq,g(a).undo,g(b).undo,f(g(a).value).undo,f(g(b).value).undo);
    }
    assert forall|x:S| #[trigger] eq((composed(x).undo)(composed(x).value),x) by {
        let first=g(x);let second=f(first.value);
        assert(eq(x,x));assert(related_maps(eq,first.undo,first.undo));
        assert(eq((second.undo)(second.value),first.value));
        assert(eq((first.undo)((second.undo)(second.value)),(first.undo)(first.value)));
        assert(eq((first.undo)(first.value),x));
    }
}

pub proof fn observational_tracking<S>(eq:spec_fn(S,S)->bool,
    e:spec_fn(S)->crate::foundations::Tracked<S>,a:crate::foundations::Tracked<S>)
    requires crate::calculus::equivalence(eq),witnessed_effect(eq,e),related_maps(eq,a.undo,a.undo),
    ensures {
        let out=e(a.value);let next=crate::foundations::Tracked {value:out.value,undo:crate::foundations::compose(a.undo,out.undo)};
        &&& eq((next.undo)(next.value),(a.undo)(a.value))
        &&& related_maps(eq,next.undo,next.undo)
    },
{
    assert(eq(a.value,a.value));assert(related_maps(eq,e(a.value).undo,e(a.value).undo));
    assert(eq((e(a.value).undo)(e(a.value).value),a.value));
    compose_related(eq,a.undo,a.undo,e(a.value).undo,e(a.value).undo);
}

/// Every reachable accumulator respects the quotient, and its recovery target
/// is invariant along a finite sequence of dynamically yielded witnesses.
pub proof fn observational_sequence_recovery<S>(eq:spec_fn(S,S)->bool,
    es:Seq<spec_fn(S)->crate::foundations::Tracked<S>>,a:crate::foundations::Tracked<S>)
    requires crate::calculus::equivalence(eq),related_maps(eq,a.undo,a.undo),
        forall|i:int| 0<=i<es.len() ==> witnessed_effect(eq,es[i]),
    ensures {
        let out=crate::foundations::apply_effects(es,a);
        &&& eq((out.undo)(out.value),(a.undo)(a.value))
        &&& related_maps(eq,out.undo,out.undo)
    },
    decreases es.len(),
{
    if es.len()>0 {
        observational_sequence_recovery(eq,es.drop_last(),a);
        let before=crate::foundations::apply_effects(es.drop_last(),a);
        assert(witnessed_effect(eq,es.last()));
        observational_tracking(eq,es.last(),before);
    }
}
} // verus!
